name: bloc_concept
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  # A dart package that helps implement the BLoC pattern.
  bloc: ^7.2.0

dev_dependencies:
  lints: ^1.0.0
